<?php

namespace AppBundle\Repository;

/**
 * CNARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CNARepository extends \Doctrine\ORM\EntityRepository
{
    //esta funcion me devuelve los contratos q ya expiraron
    public function getAllCNA($filter){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('c')
            ->from('AppBundle:CNA','c')
//            ->innerJoin('c.suplier','s')
        ;
        if($filter!=""){
            $qb
                ->where($qb->expr()->like('c.codReuup','?1'))
                ->orWhere($qb->expr()->like('c.codNit','?1'))
                ->orWhere($qb->expr()->like('c.address', '?1'))
                ->orWhere($qb->expr()->like('c.cucAccount', '?1'))
                ->orWhere($qb->expr()->like('c.cupAccount','?1'))
                ->orWhere($qb->expr()->like('c.name', '?1'))
                ->orWhere($qb->expr()->like('c.socialObject', '?1'))
                ->setParameter(1, '%' . $filter . '%')
            ;
        }/*else{
            $qb->setParameter('date',new \DateTime('today'));
        }*/
        $result = $qb->getQuery();
        return $result;
    }
}
