<?php

namespace AppBundle\Repository;

/**
 * SupplementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplementRepository extends \Doctrine\ORM\EntityRepository
{
    //esta funcion me devuelve los contratos no han expirados todavia
    public function getSupplements($filter){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('s')
            ->from('AppBundle:Supplement','s')
            ->innerJoin('s.contract','c')
            ->innerJoin('c.suplier','su')
        ;
        if($filter!=""){
            $qb
                ->where($qb->expr()->like('s.consecutiveNumber','?1'))
                ->orWhere($qb->expr()->like('s.contractualObject','?1'))
                ->orWhere($qb->expr()->like('s.description','?1'))
                ->orWhere($qb->expr()->like('s.cucValue', '?1'))
                ->orWhere($qb->expr()->like('s.cupValue', '?1'))
                ->orWhere($qb->expr()->like('c.contractualObject', '?1'))
                ->setParameter(1, '%' . $filter . '%')
            ;
        }
        $result = $qb->getQuery()->getResult();
        return $result;
    }
}
