<?php

namespace AppBundle\Repository;

/**
 * TCPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TCPRepository extends \Doctrine\ORM\EntityRepository
{
    //esta funcion me devuelve los contratos q ya expiraron
    public function getAllTcp($filter){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('t1')
            ->from('AppBundle:TCP','t1')
        ;
        if($filter!=""){
            $qb
                ->orWhere($qb->expr()->like('t1.ci', '?1'))
                ->orWhere($qb->expr()->like('t1.address', '?1'))
                ->orWhere($qb->expr()->like('t1.cucAccount', '?1'))
                ->orWhere($qb->expr()->like('t1.cupAccount','?1'))
                ->orWhere($qb->expr()->like('t1.name', '?1'))
                ->orWhere($qb->expr()->like('t1.socialObject', '?1'))
                ->setParameter(1, '%' . $filter . '%')
            ;
        }
        $result = $qb->getQuery();
        return $result;
    }

    public function checkSupplierName($supplierName){
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb
            ->select('s')
            ->from('AppBundle:Supplier','s')
            ->where('s instance of AppBundle:TCP')
            ->andWhere($qb->expr()->like('s.name', '?1'))
            ->setParameter(1, $supplierName)
        ;

        $result = $qb->getQuery()->getResult();
        return $result;
    }
}
