# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        db:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate
            http_basic: ~
            provider: db
            form_login:
                login_path: login
                check_path: login
                default_target_path: contract_index
            logout:
                path:   /logout
                target: login

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12


    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/*, roles: ROLE_ADMIN }
        - { path: ^/contract/*, roles: [ROLE_ADMIN,ROLE_USER] }
        - { path: ^/supplement/*, roles: [ROLE_ADMIN,ROLE_USER] }
        - { path: ^/department/*, roles: [ROLE_ADMIN,ROLE_USER] }
        - { path: ^/cna/*, roles: [ROLE_ADMIN,ROLE_USER] }
        - { path: ^/tcp/*, roles: [ROLE_ADMIN,ROLE_USER] }
        - { path: ^/ee/*, roles: [ROLE_ADMIN,ROLE_USER] }
#