<?php

namespace AppBundle\Command;

use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class CheckContractsCommand extends ContainerAwareCommand
{
    protected function configure()
    {
        $this
            ->setName('contract:check-contracts')
            ->setDescription('Verifica todos los contratos')
            ->setHelp('Verifica toda la lista de los contratos y cambia la cantidad de dias q le quedan al contrato')
        ;
//        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $em = $this->getContainer()->get('doctrine')->getManager();
        $contracts = $em->getRepository('AppBundle:Contract')->findAll();
        foreach ($contracts as $contract){

            $date = new \DateTime('now');

            $dif = $date->diff($contract->getExpirationDate());
            $contract->setDays($dif->days);
            $em->persist($contract);
            $em->flush();
            $output->writeln(array(
                '<info>Checking contracts.</info>',
                '<info>Checking contracts..</info>',
                '<info>Checking contracts...</info>',
            ));
        }

//        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}