<?php
/**
 * Created by PhpStorm.
 * User: javier
 * Date: 1/8/2018
 * Time: 8:48 a.m.
 */

namespace AppBundle\Command;

use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Swift_Mailer;

class SendEmailCommand extends ContainerAwareCommand
{
    protected function configure()
    {
        $this
            ->setName('contract:send-email')
            ->setDescription('Send email for expired contracts')
            ->setHelp('Envia el email para los contratos q tengan menos de 60 dias')
        ;
//        parent::configure(); // TODO: Change the autogenerated stub
    }

    public function execute(InputInterface $input, OutputInterface $output)
    {
        $em = $this->getContainer()->get('doctrine')->getManager();
        $twig = $this->getContainer()->get('twig');
        $mailer = $this->getContainer()->get('mailer');
        $contracts = $em->getRepository('AppBundle:Contract')->findContractsNextToExpire();

//        foreach ($contracts as $contract){//aqui voy a recorrer todos los contratos

            $content = $twig->render(
                'notifications/notification.html.twig',
                array('contracts' => $contracts)
            );

            //envio de notifications
            $message = (new \Swift_Message('Hello Email'))
                ->setFrom('contratos@cubanacan.tur.cu')
                ->setTo(
					'informatico4@cubanacan.tur.cu','personal1@cubanacan.tur.cu'
				)
                ->setSubject('Contratos proximos a expirar')
                ->setBody($content,
//                    $this->renderView(
//                    // app/Resources/views/Emails/registration.html.twig
//                        'Emails/registration.html.twig',
//                        array('name' => 'Javier')
//                    ),
                    'text/html'
                );
            $mailer->send($message);

            $output->writeln(array(
                '<info>Send email.</info>',
                '<info>Send email..</info>',
                '<info>Send email...</info>',
            ));
//        }

//        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}